// 本地存储前缀
export const STORAGE_PREFIX = 'MYBLOG_SYSTEM_'

// 登录key存储前缀
export const LOGIN_CONF = {
  KEY: STORAGE_PREFIX + 'LOGIN_USER_KEY',
  NAME: STORAGE_PREFIX + 'LOGIN_USER_NAME',
  LANGUAGE: STORAGE_PREFIX + 'LANGUAGE',
  THEME: STORAGE_PREFIX + 'THEME',
}
