import {
  create,
  NButton,
  NTooltip,
  NInput,
  NInputGroup,
  NInputGroupLabel,
  NGrid,
  NGi,
  NSelect,
  NDrawer,
  NDrawerContent,
  NPopover,
  NRadio,
  NRadioGroup,
  NSpace,
  NForm,
  NFormItem,
  NFormItemRow,
  NMessageProvider,
  NDialogProvider,
  NNotificationProvider,
  NConfigProvider,
  MessageApi,
  NModal,
  NScrollbar,
  NTabs,
  NTabPane,
  NSpin,
  NDivider,
  NCarousel,
  NImage,
  NImageGroup,
  NDataTable,
  NSwitch,
  NCheckbox,
  NBadge,
  DialogApi,
  NDatePicker,
  NIcon,
  NLayout,
  NLayoutSider,
  NMenu,
  NLayoutContent,
  NLayoutHeader,
  NDropdown,
  NTree,
} from 'naive-ui'

declare global {
  interface Window {
    $message: MessageApi
    $dialog: DialogApi
  }
}

const naive = create({
  components: [
    NButton,
    NTooltip,
    NInput,
    NInputGroup,
    NInputGroupLabel,
    NGrid,
    NGi,
    NSelect,
    NDrawer,
    NDrawerContent,
    NPopover,
    NRadio,
    NRadioGroup,
    NSpace,
    NForm,
    NFormItem,
    NFormItemRow,
    NMessageProvider,
    NDialogProvider,
    NNotificationProvider,
    NConfigProvider,
    NModal,
    NScrollbar,
    NTabs,
    NTabPane,
    NSpin,
    NDivider,
    NCarousel,
    NImage,
    NImageGroup,
    NDataTable,
    NSwitch,
    NCheckbox,
    NBadge,
    NDatePicker,
    NIcon,
    NLayout,
    NLayoutContent,
    NLayoutHeader,
    NLayoutSider,
    NMenu,
    NDropdown,
    NTree,
  ],
})

export default naive
